apiVersion: v1
kind: ConfigMap
metadata:
  name: cyberrepos-config
  namespace: cyberrepos-system
  labels:
    app.kubernetes.io/name: cyberrepos
    app.kubernetes.io/component: frontend
data:
  APP_ENV: "production"
  PORT: "8080"
  VITE_APP_TITLE: "CyberRepos Hub"
