apiVersion: v1
kind: Secret
metadata:
  name: cyberrepos-secrets
  namespace: cyberrepos-system
  labels:
    app.kubernetes.io/name: cyberrepos
    app.kubernetes.io/component: frontend
type: Opaque
stringData:
  VITE_SUPABASE_URL: "https://debpapifbkxxvatbhyqx.supabase.co"
  VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlYnBhcGlmYmt4eHZhdGJoeXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3NjQyOTMsImV4cCI6MjEwMjM0MDI5M30.4xpuo2bDm00-wLYjhx8_pvSmhntnPi6EBI91urpJ4s0"
